### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by reugn** [dream11/vertx-aerospike-client#17]
### Summary

https://github.com/dream11/vertx-aerospike-client/blob/master/src/test/java/io/d11/aerospike/AerospikeAddTest.java#L6
`io.d11.reactivex.aerospike.client.AerospikeClient` is not resolved in tests. It also doesn't appear to be a part of the project.

**Comment by kkaran097** [comment]
This package is generated on compilation. Please run `mvn compile` and find the generated code in `src/main/generated`
