### ISSUE TITLE
Share vertx's own eventLoopGroup instead of creating a new one

### ISSUE THREAD

**Issue by saurabhd336** [dream11/vertx-aerospike-client#22]
### Summary

https://github.com/dream11/vertx-aerospike-client/blob/3d29e77e7496575b707e8b045dba775ae278e9de/src/main/java/io/d11/aerospike/client/AerospikeConnectOptions.java#L105

Instead of creating a new eventLoopGroup exclusively for the client, should we be using vert'x own eventLoopGroup instead? I'm guessing it should improve performance as per
https://docs.aerospike.com/docs/client/java/usage/async/eventloop.html#create-netty-event-loops and due to the fact that we'll be creating fewer threads.

`private EventLoopGroup getEventLoopGroup(int size) {
    return OS.contains("linux") || OS.contains("unix") ?
        new EpollEventLoopGroup(size) : new NioEventLoopGroup(size);
  }`
  
  to
  
  `private EventLoopGroup getEventLoopGroup(Vertx vertx) {
      return vertx.nettyEventLoopGroup()
  }`
  
  The listner will no longer have to use vertx.runOnContext() since the onRecord part will already be running on vertx eventloop

**Comment by akshaypatidar1999** [comment]
Thanks @saurabhd336. We will check this and get back.

**Comment by kkaran097** [comment]
@saurabhd336 We tried sharing vertx's eventloop and it works on linux distributions. But on macOS BigSur(11), we were getting timeouts for every database call. We found that the request wasn't even submitted to any aerospike node in the cluster. We are working to verify this on other macOS versions. You may try doing this yourself and let us know if you face the same issue.

**Comment by saurabhd336** [comment]
@karan-d11 Worked for me on Catalina (10.15.7), vertx web (4.2.1), aerospike-client (5.1.8).
Same dependencies also work fine on ubuntu 18.04. Will try and check on other mac versions.

**Comment by akshaypatidar1999** [comment]
@saurabhd336 We did a performance test with vertx's own eventLoopGroup and creating a new eventLoopGroup and got similar results. As vertx's own eventLoopGroup does not work on macOS BigSur(11) we are creating new eventLoopGroup.
